version: '3.8'

services:
  app:
    build:
      context: ./www/
      dockerfile: dockerfile.php
    image: exo_docker_php:${TAG:-latest}
    container_name: app_php_docker
    ports:
      - "80:80"
    networks:
      - exo_network

  db:
    build:
      context: ./database/
      dockerfile: dockerfile.postgres
    
    container_name: postgres_exo_docker
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: gestion_produits
    
    networks:
      - exo_network

networks:
  exo_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
